### PR TITLE
UTF-8 design doc stub

### PR DESCRIPTION
**Pull request by krwq**

### CODE REVIEW

**Comment by krwq** [comment]
cc: @GrabYourPitchforks @JeffHandley

**Review by jeffhandley — APPROVED** [review]
Looks good to me, @krwq. Thank you!  When creating the PR against `dotnet/designs`, please include description notes that this is just the stub for the structure of the documentation, that we have some scenarios that we'll be adding in, but that we want each of those to be their own PRs so they can have discussions as needed.

Thanks again!

**Comment by krwq** [comment]
(squashed commits)

**Comment by krwq** [comment]
closing this PR to avoid confusion with PR against dotnet/designs

**Pull request closed without merging**
